format = """
$os\
$directory\
$git_branch\
$git_metrics\
[ ]()
"""


right_format = """
$character\
$cmd_duration\
$time\
"""

add_newline = false
palette = "catppuccin_latte"

[palettes.onedark]
base = "#ffffff"
text = "#282c34"
crust = "#abb2bf"
maroon = "#e06c75"
red = "#be5046"
green = "#98c379"
yellow = "#e5c07b"
peach = "#d19a66"
blue = "#61afef"
mauve = "#c678dd"
sapphire = "#56b6c2"
subtext1 = "#4b5263"
subtext0 = "#5c6370"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[character]
format = "[ $symbol ](bg:crust)"
success_symbol = "[](bold bg:crust fg:green)"
error_symbol = "[✖](bold bg:crust  fg:red)"

[cmd_duration]
min_time = 1_000
format = "[$duration ]($style)"
style = "bg:crust fg:text"

[directory]
format = "[ $path ]($style)[$read_only]($read_only_style)"
read_only = " R"
read_only_style = "red"
truncation_length = 5
truncate_to_repo = false
style = "bold bg:subtext1 fg:crust"

[git_branch]
format = "[ $symbol $branch(:$remote_branch) ]($style)"
style = "bold bg:subtext0 fg:crust"
symbol = ""

[git_metrics]
disabled = false
format = "[\\(](bold bg:subtext0 fg:crust)([+$added]($added_style))([-$deleted]($deleted_style))[\\) ](bold bg:subtext0 fg:crust)"
added_style = "bg:subtext0  fg:crust"
deleted_style = "bg:subtext0  fg:crust"

[time]
disabled = false
format = "[ $time ]($style)"
time_format = "%H:%M"
style = "bold bg:yellow fg:text"

[os]
disabled = false
format = "[ $symbol ]($style)"
style = "bg:text fg:crust"

[os.symbols]
Macos = ""
Ubuntu = "󰌽"
